create table if not exists farmers (
  id bigint generated by default as identity primary key,
  farmer_name text not null,
  phone text,
  lat double precision not null,
  lng double precision not null
);

create table if not exists drivers (
  id bigint generated by default as identity primary key,
  name text not null unique,
  phone text not null
);

create table if not exists assigned_routes (
  id bigint generated by default as identity primary key,
  route_title text,
  route_date date not null,
  driver_name text not null,
  driver_phone text not null,
  start_name text not null,
  end_name text not null,
  farmer_names_json text not null,
  google_maps_url text not null,
  distance_km double precision not null,
  duration text not null,
  completed boolean not null default false,
  created_at timestamp with time zone not null default now()
);

alter table farmers disable row level security;
alter table drivers disable row level security;
alter table assigned_routes disable row level security;
